name: WFTEST

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: choice
        options:
        - major
        - minor
        - patch
      overwrite:
        description: 'Version overwrite'
        type: string

jobs:
  publish:
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13'
      - name: "Version and publish" # Interesting step
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{inputs.overwrite}} ]; then
            npx lerna version ${{inputs.overwrite}} --yes
          else
            npx lerna version ${{inputs.version}} --yes
          fi
