name: WFTEST

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: choice
        options:
        - major
        - minor
        - patch
      overwrite:
        description: 'Version overwrite'
        type: string

jobs:
  publish:
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        run: if [ ${{inputs.overwrite}} ];then echo ${{inputs.overwrite}};else echo ${{inputs.version}};fi
      - name: "Version and publish" # Interesting step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{inputs.overwrite}} ]; then
            npx lerna version ${{inputs.overwrite}} --yes
          else
            npx lerna version ${{inputs.version} --yes
          fi
